package blue.language.processor;

import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Keeps the generated host-metrics catalogue aligned with the typed manifest. */
final class ProcessingMetricReferenceDocumentationTest {

    @Test
    void shouldMatchTheGeneratedHostMetricCatalog()
            throws Exception {
        // given
        Path reference = Paths.get(
                "docs", "reference", "host-metrics.md");
        List<String> expectedRows = Arrays.stream(
                        ProcessingMetricId.values())
                .map(ProcessingMetricReferenceDocumentationTest::metricRow)
                .collect(Collectors.toList());

        // when
        List<String> checkedIn = Files.readAllLines(
                reference, StandardCharsets.UTF_8);
        List<String> actualRows = checkedIn.stream()
                .filter(line -> line.startsWith("| `"))
                .collect(Collectors.toList());

        // then
        assertTrue(checkedIn.contains(
                "<!-- Generated by :generateDocumentationReferences; "
                        + "do not edit manually. -->"));
        assertEquals(expectedRows, actualRows);
        assertTrue(checkedIn.contains(
                "Total closed metric ids: **"
                        + expectedRows.size() + "**."));
    }

    private static String metricRow(ProcessingMetricId metricId) {
        ProcessingObservationDimension dimension =
                metricId.requiredDimension();
        return "| `" + metricId.name()
                + "` | `" + metricId.externalName()
                + "` | `" + metricId.kind().name()
                + "` | " + (dimension == null
                ? "—"
                : "`" + dimension.name() + "`")
                + " |";
    }
}
