package blue.language.processor;

/** Generates the machine-readable processing metric reference from the enum. */
public final class ProcessingMetricManifest {

    private ProcessingMetricManifest() {
    }

    /**
     * Renders a deterministic JSON manifest in enum declaration order.
     *
     * @return JSON metric manifest
     */
    public static String json() {
        StringBuilder json = new StringBuilder();
        json.append("{\n  \"schemaVersion\": 1,\n  \"metrics\": [\n");
        ProcessingMetricId[] metricIds = ProcessingMetricId.values();
        for (int index = 0; index < metricIds.length; index++) {
            ProcessingMetricId metricId = metricIds[index];
            json.append("    {\"id\": \"")
                    .append(metricId.name())
                    .append("\", \"name\": \"")
                    .append(metricId.externalName())
                    .append("\", \"kind\": \"")
                    .append(metricId.kind().name())
                    .append("\", \"dimension\": ");
            ProcessingObservationDimension dimension = metricId.requiredDimension();
            if (dimension == null) {
                json.append("null");
            } else {
                json.append('"').append(dimension.externalName()).append('"');
            }
            json.append('}');
            if (index + 1 < metricIds.length) {
                json.append(',');
            }
            json.append('\n');
        }
        return json.append("  ]\n}\n").toString();
    }

    /** Renders the checked-in human reference from the same closed enum. */
    static String markdown() {
        StringBuilder markdown = new StringBuilder();
        markdown.append("# Processing Observation Reference\n\n")
                .append("<!-- Generated by ProcessingMetricManifest; do not edit the table manually. -->\n\n")
                .append("Operational observations never affect Contracts semantics, portable gas, ")
                .append("provider demand, diagnostics, or commit. Exporters aggregate each metric ")
                .append("according to its typed kind and may attach only the listed bounded ")
                .append("dimension.\n\n")
                .append("| Metric | Kind | Required dimension |\n")
                .append("| --- | --- | --- |\n");
        for (ProcessingMetricId metricId : ProcessingMetricId.values()) {
            ProcessingObservationDimension dimension =
                    metricId.requiredDimension();
            markdown.append("| `")
                    .append(metricId.externalName())
                    .append("` | `")
                    .append(metricId.kind().name())
                    .append("` | ");
            if (dimension == null) {
                markdown.append("—");
            } else {
                markdown.append('`')
                        .append(dimension.externalName())
                        .append('`');
            }
            markdown.append(" |\n");
        }
        return markdown.toString();
    }
}
