package blue.language.processor;

import blue.language.model.wire.BlueLanguageConstants;

import blue.language.conformance.ConformanceEngine;
import blue.language.model.Node;
import blue.language.processor.util.PointerUtils;
import blue.language.processor.util.ProcessorContractConstants;
import blue.language.processor.util.ProcessorPointerConstants;
import blue.language.snapshot.FrozenNode;
import blue.language.model.wire.JsonPointer;
import blue.language.model.NodePath;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Enforces scope-local policy over type metadata generated by conformance.
 *
 * <p>Only generated metadata paths are inspected. A child scope may not
 * generalize outside its boundary, and a configured subtype floor is checked
 * against the final resolved root before commit.</p>
 */
final class TypeGeneralizationPolicyResolver {

    private static final String DEFAULT_MODE =
            ProcessorContractConstants.GENERALIZATION_MODE_REJECT;

    private TypeGeneralizationPolicyResolver() {
    }

    static void enforceScopeBoundary(String originScope, List<String> generatedPaths) {
        String normalizedOrigin = PointerUtils.normalizeScope(originScope);
        if (JsonPointer.ROOT.equals(normalizedOrigin)
                || generatedPaths == null
                || generatedPaths.isEmpty()) {
            return;
        }
        for (String generatedPath : generatedPaths) {
            MetadataWrite write = MetadataWrite.from(generatedPath);
            if (write == null) {
                continue;
            }
            if (!PointerUtils.descendantOrEqual(write.nodePath, normalizedOrigin)) {
                throw new ProcessorFailureException(ProcessorErrorCategory.PatchBoundaryViolation,
                        "BoundaryViolation: embedded child patch cannot generalize parent scope");
            }
        }
    }

    static void enforce(ConformanceEngine conformanceEngine,
                        FrozenNode finalResolvedRoot,
                        List<String> generatedPaths) {
        enforce(conformanceEngine,
                finalResolvedRoot,
                generatedPaths,
                JsonPointer.ROOT,
                freeze(finalResolvedRoot, JsonPointer.ROOT),
                true);
    }

    static void enforce(ConformanceEngine conformanceEngine,
                        FrozenNode finalResolvedRoot,
                        List<String> generatedPaths,
                        String originScope) {
        enforce(conformanceEngine,
                finalResolvedRoot,
                generatedPaths,
                originScope,
                freeze(finalResolvedRoot, originScope),
                true);
    }

    static FrozenPolicy freeze(
            FrozenNode prePatchResolvedRoot,
            String originScope) {
        if (prePatchResolvedRoot == null) {
            return FrozenPolicy.absent(originScope);
        }
        Node root = prePatchResolvedRoot.toNode();
        String normalizedOrigin = PointerUtils.normalizeScope(originScope);
        Policy scopedPolicy = Policy.from(root, normalizedOrigin);
        Policy rootPolicy = JsonPointer.ROOT.equals(normalizedOrigin)
                ? scopedPolicy
                : Policy.from(root, JsonPointer.ROOT);
        return new FrozenPolicy(scopedPolicy, rootPolicy);
    }

    static void enforce(ConformanceEngine conformanceEngine,
                        FrozenNode finalResolvedRoot,
                        List<String> generatedPaths,
                        String originScope,
                        FrozenPolicy frozenPolicy,
                        boolean requireExplicitPolicy) {
        if (finalResolvedRoot == null
                || generatedPaths == null || generatedPaths.isEmpty()) {
            return;
        }
        Node root = finalResolvedRoot.toNode();
        FrozenPolicy policySnapshot = Objects.requireNonNull(
                frozenPolicy, "frozenPolicy");
        for (String generatedPath : generatedPaths) {
            MetadataWrite write = MetadataWrite.from(generatedPath);
            if (write == null) {
                continue;
            }
            Policy policy = policySnapshot.policyFor(write.nodePath);
            if (!policy.present && !requireExplicitPolicy) {
                /*
                 * Contracts 1.0 introduced fail-closed policy admission for
                 * application-contract evolution.  Ordinary value patches
                 * that already used Language conformance widening remain a
                 * compatibility lane when no policy exists.  An explicitly
                 * configured policy still governs both lanes.
                 */
                continue;
            }
            Rule rule = policy.ruleFor(write.nodePath);
            String mode = rule != null && rule.mode != null ? rule.mode : policy.defaultMode;
            if (ProcessorContractConstants
                    .GENERALIZATION_MODE_REJECT.equals(mode)) {
                throw new ProcessorFailureException(ProcessorErrorCategory.TypeGeneralizationFailure,
                        "GeneralizationRejected: type generalization policy rejects " + write.nodePath);
            }
            String floor = rule != null ? rule.mustRemainSubtypeOf : null;
            if (floor == null) {
                continue;
            }
            String generatedType = metadataBlueId(root, generatedPath);
            boolean withinFloor = conformanceEngine != null
                    && generatedType != null
                    && (Objects.equals(generatedType, floor)
                    || conformanceEngine.isSubtypeOf(generatedType, floor));
            if (!withinFloor) {
                throw new ProcessorFailureException(ProcessorErrorCategory.TypeGeneralizationFailure,
                        "GeneralizationRejected: type generalization would cross policy floor");
            }
        }
    }

    /** Immutable policy view captured before the requiring authored patch. */
    static final class FrozenPolicy {
        private final Policy scopedPolicy;
        private final Policy rootPolicy;

        private FrozenPolicy(Policy scopedPolicy, Policy rootPolicy) {
            this.scopedPolicy = Objects.requireNonNull(
                    scopedPolicy, "scopedPolicy");
            this.rootPolicy = Objects.requireNonNull(
                    rootPolicy, "rootPolicy");
        }

        private static FrozenPolicy absent(String originScope) {
            String normalizedOrigin = PointerUtils.normalizeScope(originScope);
            Policy scoped = Policy.absent(normalizedOrigin);
            Policy root = JsonPointer.ROOT.equals(normalizedOrigin)
                    ? scoped
                    : Policy.absent(JsonPointer.ROOT);
            return new FrozenPolicy(scoped, root);
        }

        private Policy policyFor(String pointer) {
            return scopedPolicy.appliesTo(pointer)
                    ? scopedPolicy
                    : rootPolicy;
        }
    }

    private static String metadataBlueId(Node root, String pointer) {
        Node node = nodeAt(root, pointer);
        return node != null ? node.getBlueId() : null;
    }

    private static Node nodeAt(Node root, String pointer) {
        if (root == null) {
            return null;
        }
        try {
            return NodePath.getNode(root, pointer);
        } catch (RuntimeException ex) {
            return null;
        }
    }

    private static final class Policy {
        private final boolean present;
        private final String scope;
        private final String defaultMode;
        private final List<Rule> rules;

        private Policy(boolean present, String scope, String defaultMode, List<Rule> rules) {
            this.present = present;
            this.scope = scope;
            this.defaultMode = defaultMode != null ? defaultMode : DEFAULT_MODE;
            this.rules = rules;
        }

        private static Policy from(Node root, String scope) {
            String normalizedScope = PointerUtils.normalizeScope(scope);
            String markerPath = PointerUtils.resolvePointer(
                    normalizedScope,
                    ProcessorPointerConstants.RELATIVE_GENERALIZATION);
            Node marker = nodeAt(root, markerPath);
            if (marker == null) {
                return absent(normalizedScope);
            }
            String defaultMode = textField(
                    marker,
                    ProcessorContractConstants.KEY_DEFAULT_MODE);
            Node rulesNode = field(
                    marker,
                    ProcessorContractConstants.KEY_RULES);
            List<Rule> rules = new ArrayList<>();
            if (rulesNode != null && rulesNode.getItems() != null) {
                for (Node item : rulesNode.getItems()) {
                    String path = textField(
                            item,
                            ProcessorContractConstants.KEY_PATH);
                    if (path != null) {
                        rules.add(new Rule(PointerUtils.resolvePointer(normalizedScope, path),
                                textField(
                                        item,
                                        ProcessorContractConstants.KEY_MODE),
                                blueIdField(
                                        item,
                                        ProcessorContractConstants
                                                .KEY_MUST_REMAIN_SUBTYPE_OF)));
                    }
                }
            }
            return new Policy(true, normalizedScope, defaultMode, rules);
        }

        private static Policy absent(String normalizedScope) {
            return new Policy(false,
                    PointerUtils.normalizeScope(normalizedScope),
                    DEFAULT_MODE,
                    java.util.Collections.<Rule>emptyList());
        }

        private boolean appliesTo(String pointer) {
            return present && PointerUtils.descendantOrEqual(pointer, scope);
        }

        private Rule ruleFor(String pointer) {
            Rule best = null;
            for (Rule rule : rules) {
                if (!PointerUtils.descendantOrEqual(pointer, rule.path)) {
                    continue;
                }
                if (best == null || rule.path.length() > best.path.length()) {
                    best = rule;
                }
            }
            return best;
        }
    }

    private static final class Rule {
        private final String path;
        private final String mode;
        private final String mustRemainSubtypeOf;

        private Rule(String path, String mode, String mustRemainSubtypeOf) {
            this.path = path;
            this.mode = mode;
            this.mustRemainSubtypeOf = mustRemainSubtypeOf;
        }
    }

    private static final class MetadataWrite {
        private final String nodePath;

        private MetadataWrite(String nodePath) {
            this.nodePath = nodePath;
        }

        private static MetadataWrite from(String pointer) {
            List<String> segments = JsonPointer.split(PointerUtils.normalizePointer(pointer));
            if (segments.isEmpty()) {
                return null;
            }
            String last = segments.get(segments.size() - 1);
            if (!isMetadataField(last)) {
                return null;
            }
            List<String> nodeSegments = segments.subList(0, segments.size() - 1);
            return new MetadataWrite(JsonPointer.toPointer(nodeSegments));
        }

        private static boolean isMetadataField(String field) {
            return BlueLanguageConstants.OBJECT_TYPE.equals(field)
                    || BlueLanguageConstants.OBJECT_ITEM_TYPE.equals(field)
                    || BlueLanguageConstants.OBJECT_KEY_TYPE.equals(field)
                    || BlueLanguageConstants.OBJECT_VALUE_TYPE.equals(field);
        }
    }

    private static String textField(Node node, String key) {
        Node field = field(node, key);
        Object value = field != null ? field.getValue() : null;
        return value != null ? String.valueOf(value) : null;
    }

    private static String blueIdField(Node node, String key) {
        Node field = field(node, key);
        if (field == null) {
            return null;
        }
        if (field.getBlueId() != null) {
            return field.getBlueId();
        }
        Object value = field.getValue();
        if (value != null) {
            return String.valueOf(value);
        }
        Node nested = field(field, BlueLanguageConstants.OBJECT_BLUE_ID);
        Object nestedValue = nested != null ? nested.getValue() : null;
        return nestedValue != null ? String.valueOf(nestedValue) : null;
    }

    private static Node field(Node node, String key) {
        return node != null && node.getProperties() != null ? node.getProperties().get(key) : null;
    }
}
