package blue.contracts.closure;
public enum ClosureProcessStatus { SUCCESS, NO_MATCH, STALE, TERMINATED, INVALID_PROCESSING_DOCUMENT, CAPABILITY_FAILURE, RUNTIME_FATAL, GAS_LIMIT_EXCEEDED, PORTABLE_LIMIT_EXCEEDED, SUBSCRIPTION_SURFACE_INVALID }
