package blue.contracts.closure;
public enum WorkKind { EXTERNAL_DELIVERY, INITIALIZATION, DOCUMENT_UPDATE, TRIGGERED_EVENT, EMBEDDED_EVENT, LIFECYCLE, HISTORICAL_TRANSITION, CONTAINING_REFERENCE_UPDATE }
