package blue.buildlogic.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.gradle.api.GradleException;

/** Renders reproducible Markdown references from compiled and conformance evidence. */
public final class DocumentationReferences {

    public static final String SCHEMA = "blue-language-java-generated-documentation/1.0";
    public static final String MARKER =
            "<!-- Generated by :generateDocumentationReferences; do not edit manually. -->";
    public static final List<String> OUTPUT_PATHS = Collections.unmodifiableList(
            java.util.Arrays.asList(
                    "architecture/modules-and-dependencies.md",
                    "reference/conformance-fixtures.md",
                    "reference/gas-counters.md",
                    "reference/host-metrics.md",
                    "reference/packages.md",
                    "reference/public-api.md",
                    "reference/runtime-spi.md",
                    "reference/statuses-and-diagnostics.md"));

    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Pattern STRING_CONSTANT = Pattern.compile(
            "(?m)^\\s*public\\s+static\\s+final\\s+String\\s+([A-Z][A-Z0-9_]*)\\s*="
                    + "\\s*\"([^\"]*)\"\\s*;");
    private static final Pattern STATUS_CONSTANT = Pattern.compile(
            "(?m)^\\s*([A-Z][A-Z0-9_]*)\\s*\\(([^)]*)\\)\\s*[,;]");
    private static final Pattern ENUM_CONSTANT = Pattern.compile(
            "(?m)^\\s{4}([A-Z][A-Za-z0-9_]*)\\s*(?:\\([^;]*?\\))?\\s*[,;]?\\s*$");
    private static final Pattern METRIC_CONSTANT = Pattern.compile(
            "(?m)^\\s{4}([A-Z][A-Z0-9_]*)\\(\"([^\"]+)\",\\s*"
                    + "ObservationKind\\.([A-Z_]+)(?:,\\s*(?:\\R\\s*)?"
                    + "ProcessingObservationDimension\\.([A-Z_]+))?\\)\\s*[,;]");
    private static final Pattern API_MODULE = Pattern.compile("(?m)^# module: (.+)$");

    private DocumentationReferences() {}

    /** Produces every generated path and its exact UTF-8 Markdown content. */
    public static Map<String, String> render(
            Path repositoryRoot,
            Collection<Path> apiInventories,
            Collection<Path> productionSources,
            Path gasManifest,
            Path releaseConformanceReport,
            Path moduleStructureReport) {
        JavaSourceQuality.Analysis source =
                JavaSourceQuality.analyze(repositoryRoot, productionSources);
        List<ApiInventory> api = apiInventories(apiInventories);
        JsonNode conformance = json(releaseConformanceReport, "release conformance report");
        JsonNode modules = json(moduleStructureReport, "module structure report");

        Map<String, String> references = new TreeMap<>();
        references.put("architecture/modules-and-dependencies.md", moduleGraph(modules));
        references.put("reference/conformance-fixtures.md", fixtureCoverage(conformance));
        references.put("reference/gas-counters.md", gasCounters(gasManifest));
        references.put("reference/host-metrics.md", hostMetrics(source));
        references.put("reference/packages.md", packages(source));
        references.put("reference/public-api.md", publicApi(api));
        references.put("reference/runtime-spi.md", runtimeSpi(api));
        references.put("reference/statuses-and-diagnostics.md", statuses(source));
        if (!references.keySet().equals(new TreeSet<>(OUTPUT_PATHS))) {
            throw new GradleException("Generated documentation path registry is incomplete");
        }
        return Collections.unmodifiableMap(references);
    }

    private static String publicApi(List<ApiInventory> inventories) {
        StringBuilder markdown = header("Public API inventory");
        markdown.append("This distribution inventory is derived from Java 8 class artifacts. ")
                .append("Descriptors are the authoritative binary signatures.\n\n")
                .append("| Module | Types | Methods | Fields | Total entries |\n")
                .append("| --- | ---: | ---: | ---: | ---: |\n");
        int totalTypes = 0;
        int totalMethods = 0;
        int totalFields = 0;
        for (ApiInventory inventory : inventories) {
            int types = inventory.count("type ");
            int methods = inventory.count("method ");
            int fields = inventory.count("field ");
            totalTypes += types;
            totalMethods += methods;
            totalFields += fields;
            markdown.append("| `").append(inventory.module).append("` | ")
                    .append(types).append(" | ").append(methods).append(" | ")
                    .append(fields).append(" | ").append(inventory.entries.size())
                    .append(" |\n");
        }
        markdown.append("| **Distribution** | **").append(totalTypes).append("** | **")
                .append(totalMethods).append("** | **").append(totalFields)
                .append("** | **").append(totalTypes + totalMethods + totalFields)
                .append("** |\n\n");
        for (ApiInventory inventory : inventories) {
            markdown.append("## ").append(inventory.module).append("\n\n```text\n");
            for (String entry : inventory.entries) {
                markdown.append(entry).append('\n');
            }
            markdown.append("```\n\n");
        }
        return markdown.toString();
    }

    private static String packages(JavaSourceQuality.Analysis source) {
        StringBuilder markdown = header("Package and type inventory");
        markdown.append("Package ownership is derived from production Java source files. ")
                .append("Only top-level public types appear below.\n\n")
                .append("| Package | Public types | `package-info.java` |\n")
                .append("| --- | ---: | --- |\n");
        for (Map.Entry<String, List<String>> entry : source.publicTypesByPackage().entrySet()) {
            markdown.append("| `").append(entry.getKey()).append("` | ")
                    .append(entry.getValue().size()).append(" | ")
                    .append(source.packagesWithPackageInfo().contains(entry.getKey())
                            ? "present" : "**missing**")
                    .append(" |\n");
        }
        markdown.append("\n");
        for (Map.Entry<String, List<String>> entry : source.publicTypesByPackage().entrySet()) {
            markdown.append("## `").append(entry.getKey()).append("`\n\n");
            for (String type : entry.getValue()) {
                markdown.append("- `").append(type).append("`\n");
            }
            markdown.append('\n');
        }
        return markdown.toString();
    }

    private static String runtimeSpi(List<ApiInventory> inventories) {
        Set<String> extensionTypes = new TreeSet<>();
        for (ApiInventory inventory : inventories) {
            for (String entry : inventory.entries) {
                if (!entry.startsWith("type ")) {
                    continue;
                }
                String type = token(entry, 1);
                boolean extensionShape = entry.contains("interface") || entry.contains("abstract");
                if (extensionShape && isRuntimeExtensionName(type)) {
                    extensionTypes.add(type);
                }
            }
        }
        StringBuilder markdown = header("Runtime SPI registry");
        markdown.append("This registry contains public interface or abstract extension surfaces ")
                .append("in provider, runtime, mapping, processor, codec, and observation roles. ")
                .append("Concrete runtime semantics remain host-owned.\n\n")
                .append("| SPI type | Role family |\n")
                .append("| --- | --- |\n");
        for (String type : extensionTypes) {
            markdown.append("| `").append(type).append("` | ")
                    .append(roleFamily(type)).append(" |\n");
        }
        markdown.append("\nTotal registered extension surfaces: **")
                .append(extensionTypes.size()).append("**.\n");
        return markdown.toString();
    }

    private static String statuses(JavaSourceQuality.Analysis source) {
        Map<String, String> constants = stringConstants(source);
        String statusSource = content(source, "ProcessorStatus.java");
        String categorySource = content(source, "ProcessorErrorCategory.java");
        String detailSource = content(source, "ProcessorDiagnosticConstants.java");

        StringBuilder markdown = header("Contracts statuses and diagnostics");
        markdown.append("Statuses and diagnostic categories are protocol-facing deterministic ")
                .append("values. Diagnostic prose and details must exclude host stack traces, ")
                .append("exception class names, cache state, and transport details. See the ")
                .append("[debugging and diagnostics guide](../guides/debugging-and-diagnostics.md) ")
                .append("for host-side handling.\n\n")
                .append("## Completed processor statuses\n\n")
                .append("| Java constant | Wire value | Commits | Meaning and recovery |\n")
                .append("| --- | --- | --- | --- |\n");
        Matcher status = STATUS_CONSTANT.matcher(enumPrefix(statusSource, "ProcessorStatus"));
        while (status.find()) {
            String name = status.group(1);
            String expression = status.group(2).trim();
            String wire = resolveString(expression, constants);
            markdown.append("| `").append(name).append("` | `")
                    .append(wire).append("` | ")
                    .append("SUCCESS".equals(name) ? "yes" : "no").append(" | ")
                    .append(statusExplanation(name)).append(" |\n");
        }
        markdown.append("\n## When `diagnostic()` is populated\n\n")
                .append("`SUCCESS`, `NO_MATCH`, `STALE`, and `TERMINATED` are ordinary completed ")
                .append("outcomes and processor-produced results carry no diagnostic. The six ")
                .append("deterministic failure statuses carry a `ProcessorDiagnostic`; the first ")
                .append("failure wins and every noncommitting result returns the unchanged input ")
                .append("Root and an empty Root-event sequence. Resource acquisition is different: ")
                .append("`PROCESS_ATTEMPT` suspends with `NeedsResources` and does not manufacture a ")
                .append("completed status or diagnostic.\n\n")
                .append("A diagnostic has a closed `ProcessorErrorCategory`, optional deterministic ")
                .append("prose, and an insertion-stable map whose keys come from the table below. ")
                .append("It never contains a stack trace, Java exception type, clock value, cache ")
                .append("state, transport fact, or provider latency. Equivalent Blue inputs, ")
                .append("evidence, registry, limits, and gas schedule therefore produce the same ")
                .append("category and details in JavaScript or any other conforming implementation.\n\n")
                .append("### `PORTABLE_LIMIT_EXCEEDED`\n\n")
                .append("This rejects a value that exceeds a fixed Contracts portable cardinality, ")
                .append("depth, text-size, pointer-size, patch/event, scope, or runtime-ledger bound. ")
                .append("The check happens before the bounded semantic work. Its diagnostic category ")
                .append("identifies the limit family and details include `limitName`, `observed`, and ")
                .append("`limit`. Recovery means reducing or partitioning the logical input/work, or ")
                .append("moving to a later specification that defines another portable bound. Raising ")
                .append("the gas budget, warming caches, changing provider layout, or retrying identical ")
                .append("input cannot change this deterministic result.\n\n")
                .append("### `SUBSCRIPTION_SURFACE_INVALID`\n\n")
                .append("This rejects the tentative commit when the effective external Channel ")
                .append("subscription surface cannot be represented as a finite canonical delta or ")
                .append("violates interval, scope, contract-binding, or revision rules. The diagnostic ")
                .append("uses `SubscriptionSurfaceInvalid` (or the more specific law category) and may ")
                .append("include `scopePath` and `contractKey`. Recovery means correcting the Channel, ")
                .append("Handler, subscription declaration, or supplied ordering evidence. It is not ")
                .append("gas exhaustion or physical index maintenance: more gas, cache changes, backend ")
                .append("layout, and an identical retry cannot make the same invalid surface commit.\n\n")
                .append("## Diagnostic categories\n\n");
        for (String category : enumConstants(categorySource, "ProcessorErrorCategory")) {
            markdown.append("- `").append(category).append("`\n");
        }
        markdown.append("\n## Stable detail fields\n\n")
                .append("| Constant | Serialized key |\n")
                .append("| --- | --- |\n");
        Matcher details = STRING_CONSTANT.matcher(detailSource);
        while (details.find()) {
            markdown.append("| `").append(details.group(1)).append("` | `")
                    .append(details.group(2)).append("` |\n");
        }
        return markdown.toString();
    }

    private static String gasCounters(Path gasManifest) {
        GasCatalog gas = parseGas(gasManifest);
        StringBuilder markdown = header("Contracts gas counter catalog");
        markdown.append("The schedule is semantic release input. Charges are admitted before ")
                .append("their logical work and physical provider/cache activity is zero portable gas.\n\n")
                .append("Schedule: `").append(gas.schedule).append("`; maximum process gas: **")
                .append(gas.maxProcessGas).append("**.\n\n")
                .append("| Namespace | Counter | Weight |\n")
                .append("| --- | --- | ---: |\n");
        for (Map.Entry<String, Map<String, String>> namespace : gas.counters.entrySet()) {
            for (Map.Entry<String, String> counter : namespace.getValue().entrySet()) {
                markdown.append("| `").append(namespace.getKey()).append("` | `")
                        .append(counter.getKey()).append("` | ")
                        .append(counter.getValue()).append(" |\n");
            }
        }
        markdown.append("\n## Portable limits\n\n| Limit | Value |\n| --- | ---: |\n");
        for (Map.Entry<String, String> limit : gas.portableLimits.entrySet()) {
            markdown.append("| `").append(limit.getKey()).append("` | ")
                    .append(limit.getValue()).append(" |\n");
        }
        return markdown.toString();
    }

    private static String hostMetrics(JavaSourceQuality.Analysis source) {
        String metrics = content(source, "ProcessingMetricId.java");
        String prefix = metrics.contains("private static")
                ? metrics.substring(0, metrics.indexOf("private static")) : metrics;
        Matcher matcher = METRIC_CONSTANT.matcher(prefix);
        StringBuilder markdown = header("Host metrics catalog");
        markdown.append("Operational host metrics are non-semantic: they do not affect BlueIds, ")
                .append("portable gas, diagnostics, provider demand, or commit decisions.\n\n")
                .append("| Metric id | External name | Aggregation | Required dimension |\n")
                .append("| --- | --- | --- | --- |\n");
        int count = 0;
        while (matcher.find()) {
            count++;
            markdown.append("| `").append(matcher.group(1)).append("` | `")
                    .append(matcher.group(2)).append("` | `")
                    .append(matcher.group(3)).append("` | ")
                    .append(matcher.group(4) == null ? "—" : "`" + matcher.group(4) + "`")
                    .append(" |\n");
        }
        markdown.append("\nTotal closed metric ids: **").append(count).append("**.\n");
        return markdown.toString();
    }

    private static String fixtureCoverage(JsonNode report) {
        requireSchema(report, "blue-language-java-release-conformance-report/1.0",
                "release conformance report");
        Map<String, Integer> suites = new TreeMap<>();
        Map<String, Integer> categories = new TreeMap<>();
        for (JsonNode fixture : report.path("fixtures")) {
            increment(suites, fixture.path("suite").asText("<missing>"));
            increment(categories, fixture.path("suite").asText("<missing>") + ":"
                    + fixture.path("category").asText("<missing>"));
        }
        StringBuilder markdown = header("Conformance fixture coverage");
        markdown.append("Release package: `")
                .append(report.path("release").path("name").asText()).append("`\n\n")
                .append("Package identity: `")
                .append(report.path("release").path("packageIdentity").asText())
                .append("`\n\n")
                .append("| Suite | Fixture count |\n| --- | ---: |\n");
        suites.forEach((suite, count) -> markdown.append("| `").append(suite)
                .append("` | ").append(count).append(" |\n"));
        markdown.append("\n## Package identities\n\n| Input | Identity |\n| --- | --- |\n");
        report.path("packages").fields().forEachRemaining(entry -> markdown.append("| `")
                .append(entry.getKey()).append("` | `").append(entry.getValue().asText())
                .append("` |\n"));
        markdown.append("\n## Specification hashes\n\n| Specification | SHA-256 |\n| --- | --- |\n");
        report.path("specifications").fields().forEachRemaining(entry -> markdown.append("| `")
                .append(entry.getKey()).append("` | `").append(entry.getValue().asText())
                .append("` |\n"));
        markdown.append("\n## Category coverage\n\n| Suite and category | Fixtures |\n| --- | ---: |\n");
        categories.forEach((category, count) -> markdown.append("| `").append(category)
                .append("` | ").append(count).append(" |\n"));
        return markdown.toString();
    }

    private static String moduleGraph(JsonNode report) {
        requireSchema(report, "blue-java-module-structure/1.0", "module structure report");
        StringBuilder markdown = header("Modules and dependencies");
        markdown.append("This graph is generated from compiled ownership inventories. ")
                .append("An arrow means the source module references the target module.\n\n")
                .append("```mermaid\ngraph LR\n");
        for (JsonNode module : report.path("modules")) {
            markdown.append("  ").append(nodeId(module.asText())).append("[\"")
                    .append(module.asText()).append("\"]\n");
        }
        for (JsonNode edge : report.path("observedEdges")) {
            markdown.append("  ").append(nodeId(edge.path("source").asText()))
                    .append(" --> ").append(nodeId(edge.path("target").asText())).append('\n');
        }
        markdown.append("```\n\n| Source module | Target module |\n| --- | --- |\n");
        for (JsonNode edge : report.path("observedEdges")) {
            markdown.append("| `").append(edge.path("source").asText()).append("` | `")
                    .append(edge.path("target").asText()).append("` |\n");
        }
        markdown.append("\nModule cycles: **").append(report.path("cycles").size())
                .append("**; split packages: **").append(report.path("splitPackages").size())
                .append("**; undeclared edges: **")
                .append(report.path("undeclaredEdges").size()).append("**.\n");
        return markdown.toString();
    }

    private static List<ApiInventory> apiInventories(Collection<Path> files) {
        List<ApiInventory> inventories = new ArrayList<>();
        for (Path file : files) {
            if (!Files.isRegularFile(file)) {
                continue;
            }
            String content = read(file, "public API inventory");
            Matcher module = API_MODULE.matcher(content);
            if (!module.find()) {
                throw new GradleException("Public API inventory has no module header: " + file);
            }
            List<String> entries = new ArrayList<>();
            for (String line : content.split("\\R")) {
                if (!line.isBlank() && !line.startsWith("#")) {
                    entries.add(line);
                }
            }
            Collections.sort(entries);
            inventories.add(new ApiInventory(module.group(1).trim(), entries));
        }
        inventories.sort(Comparator.comparing(value -> value.module));
        if (inventories.isEmpty()) {
            throw new GradleException("Generated documentation requires public API inventories");
        }
        return inventories;
    }

    private static Map<String, String> stringConstants(JavaSourceQuality.Analysis source) {
        Map<String, String> constants = new TreeMap<>();
        for (JavaSourceQuality.SourceFile file : source.files()) {
            Matcher matcher = STRING_CONSTANT.matcher(read(file.sourcePath(), "constant"));
            while (matcher.find()) {
                constants.put(matcher.group(1), matcher.group(2));
            }
        }
        return constants;
    }

    private static String content(JavaSourceQuality.Analysis source, String fileName) {
        for (JavaSourceQuality.SourceFile file : source.files()) {
            if (file.relativePath().endsWith("/" + fileName)) {
                return read(file.sourcePath(), fileName);
            }
        }
        throw new GradleException("Generated documentation input is missing " + fileName);
    }

    private static String enumPrefix(String source, String enumName) {
        int declaration = source.indexOf("enum " + enumName);
        if (declaration < 0) {
            throw new GradleException("Cannot find enum " + enumName);
        }
        int method = source.indexOf("private final", declaration);
        return method < 0 ? source.substring(declaration) : source.substring(declaration, method);
    }

    private static List<String> enumConstants(String source, String enumName) {
        String prefix = enumPrefix(source, enumName);
        List<String> constants = new ArrayList<>();
        Matcher matcher = ENUM_CONSTANT.matcher(prefix);
        while (matcher.find()) {
            String value = matcher.group(1);
            if (!value.equals(enumName)) {
                constants.add(value);
            }
        }
        return constants;
    }

    private static String resolveString(String expression, Map<String, String> constants) {
        if (expression.startsWith("\"") && expression.endsWith("\"")) {
            return expression.substring(1, expression.length() - 1);
        }
        String name = expression.substring(expression.lastIndexOf('.') + 1);
        return constants.getOrDefault(name, expression);
    }

    private static String statusExplanation(String name) {
        switch (name) {
            case "SUCCESS":
                return "The run completed; adopt the returned Root and ordered Root emissions.";
            case "NO_MATCH":
                return "No eligible Channel/Handler delivery matched; the input Root remains current.";
            case "STALE":
                return "Ordering or revision evidence was stale; refresh evidence before a new attempt.";
            case "TERMINATED":
                return "A processor-managed termination marker stopped the Root; do not retry unchanged state.";
            case "INVALID_PROCESSING_DOCUMENT":
                return "Root, event, reserved state, or execution evidence failed deterministic admission; fix the input.";
            case "CAPABILITY_FAILURE":
                return "A required must-understand runtime capability was unsupported or invalid; register/fix that capability.";
            case "RUNTIME_FATAL":
                return "A registered runtime implementation failed deterministically; fix its implementation or input.";
            case "GAS_LIMIT_EXCEEDED":
                return "The next semantic charge exceeded the admitted budget; reduce work or explicitly raise that budget.";
            case "PORTABLE_LIMIT_EXCEEDED":
                return "A specification-wide size/cardinality bound was exceeded; reduce or partition logical work.";
            case "SUBSCRIPTION_SURFACE_INVALID":
                return "The tentative external-subscription delta violated canonical surface laws; fix the declaration/evidence.";
            default:
                throw new GradleException("Missing generated explanation for ProcessorStatus." + name);
        }
    }

    private static boolean isRuntimeExtensionName(String type) {
        String lower = type.toLowerCase(Locale.ROOT);
        return lower.contains(".provider.")
                || lower.contains(".runtime.")
                || lower.contains(".mapping.")
                || lower.contains(".processor.")
                || lower.contains(".codec.")
                || lower.matches(".*(provider|runtime|handler|channel|observer|resolver|codec|spi)$");
    }

    private static String roleFamily(String type) {
        String lower = type.toLowerCase(Locale.ROOT);
        if (lower.contains("provider")) return "provider/evidence";
        if (lower.contains("channel")) return "channel";
        if (lower.contains("handler")) return "handler";
        if (lower.contains("observer") || lower.contains("metric")) return "observation";
        if (lower.contains("codec")) return "codec";
        if (lower.contains("mapping") || lower.contains("resolver")) return "mapping/resolution";
        if (lower.contains("runtime")) return "runtime";
        return "processor extension";
    }

    private static GasCatalog parseGas(Path manifest) {
        List<String> lines;
        try {
            lines = Files.readAllLines(manifest, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new GradleException("Cannot read Contracts gas manifest: " + manifest, exception);
        }
        String schedule = "<missing>";
        String maxProcessGas = "<missing>";
        Map<String, Map<String, String>> counters = new TreeMap<>();
        Map<String, String> limits = new TreeMap<>();
        String section = "";
        String namespace = null;
        boolean inCounters = false;
        for (String line : lines) {
            if (line.startsWith("schedule:")) schedule = scalar(line);
            if (line.startsWith("maxProcessGas:")) maxProcessGas = scalar(line);
            if (line.equals("namespaces:")) {
                section = "namespaces";
                namespace = null;
                inCounters = false;
            } else if (line.equals("portableLimits:")) {
                section = "portableLimits";
                namespace = null;
                inCounters = false;
            } else if ("namespaces".equals(section) && line.matches("  [A-Za-z0-9_-]+:")) {
                namespace = line.trim().replace(":", "");
                counters.putIfAbsent(namespace, new TreeMap<>());
                inCounters = false;
            } else if ("namespaces".equals(section) && line.trim().equals("counters:")) {
                inCounters = true;
            } else if ("namespaces".equals(section) && inCounters
                    && namespace != null && line.matches("      [A-Za-z0-9_-]+:.*")) {
                keyValue(line.trim(), counters.get(namespace));
            } else if ("portableLimits".equals(section)
                    && line.matches("  [A-Za-z0-9_-]+:.*")) {
                keyValue(line.trim(), limits);
            } else if (!line.isBlank() && !line.startsWith(" ")) {
                section = "";
                namespace = null;
                inCounters = false;
            }
        }
        return new GasCatalog(schedule, maxProcessGas, counters, limits);
    }

    private static void keyValue(String line, Map<String, String> output) {
        int separator = line.indexOf(':');
        output.put(line.substring(0, separator).trim(), line.substring(separator + 1).trim());
    }

    private static String scalar(String line) {
        return line.substring(line.indexOf(':') + 1).trim().replace("'", "");
    }

    private static String read(Path file, String description) {
        try {
            return Files.readString(file, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new GradleException("Cannot read " + description + ": " + file, exception);
        }
    }

    private static JsonNode json(Path file, String description) {
        try {
            return JSON.readTree(file.toFile());
        } catch (IOException exception) {
            throw new GradleException("Cannot read " + description + ": " + file, exception);
        }
    }

    private static void requireSchema(JsonNode report, String schema, String description) {
        if (!schema.equals(report.path("schema").asText())) {
            throw new GradleException("Unsupported " + description + " schema");
        }
    }

    private static StringBuilder header(String title) {
        return new StringBuilder("# ").append(title).append("\n\n")
                .append(MARKER).append("\n\n")
                .append("Schema: `").append(SCHEMA).append("`.\n\n");
    }

    private static String token(String value, int index) {
        String[] parts = value.split(" ");
        return index < parts.length ? parts[index] : "";
    }

    private static String nodeId(String module) {
        return "m_" + module.replace('-', '_').replace('.', '_');
    }

    private static void increment(Map<String, Integer> values, String key) {
        values.put(key, values.getOrDefault(key, 0) + 1);
    }

    private static final class ApiInventory {
        private final String module;
        private final List<String> entries;

        private ApiInventory(String module, List<String> entries) {
            this.module = module;
            this.entries = entries;
        }

        private int count(String prefix) {
            return (int) entries.stream().filter(value -> value.startsWith(prefix)).count();
        }
    }

    private static final class GasCatalog {
        private final String schedule;
        private final String maxProcessGas;
        private final Map<String, Map<String, String>> counters;
        private final Map<String, String> portableLimits;

        private GasCatalog(
                String schedule,
                String maxProcessGas,
                Map<String, Map<String, String>> counters,
                Map<String, String> portableLimits) {
            this.schedule = schedule;
            this.maxProcessGas = maxProcessGas;
            this.counters = counters;
            this.portableLimits = portableLimits;
        }
    }
}
