package blue.buildlogic.support;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.gradle.api.GradleException;

/** Detects source changes made after release evidence was generated. */
public final class StaleInputVerifier {

    private static final Pattern SOURCE_IDENTITY = Pattern.compile(
            "\\\"sourceInputIdentity\\\"\\s*:\\s*\\\"(sha256:[0-9a-f]{64})\\\"");

    private StaleInputVerifier() {}

    public static void assertCurrent(String recordedIdentity, String currentIdentity) {
        if (!recordedIdentity.equals(currentIdentity)) {
            throw new GradleException(
                    "Release evidence is stale: recorded source input identity "
                            + recordedIdentity
                            + " differs from current identity "
                            + currentIdentity);
        }
    }

    /** Extracts the source identity from evidence generated by this build logic. */
    public static String sourceIdentityFrom(String evidenceJson) {
        Matcher matcher = SOURCE_IDENTITY.matcher(evidenceJson);
        if (!matcher.find()) {
            throw new GradleException(
                    "Release evidence does not contain a valid sourceInputIdentity");
        }
        return matcher.group(1);
    }
}
