name: Release

on:
  workflow_dispatch:
   inputs:
    tag:
      description: 'Release tag'
      required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          if git show-ref --tags | grep -q "refs/tags/$TAG$"; then
            echo "Tag $TAG exists."
          else
            echo "Tag $TAG does not exist."
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew clean build
    
      - name: Execute Gradle publish
        run: ./gradlew publish

      - name: Execute Gradle release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: ./gradlew jreleaserFullRelease

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build/libs
            build/publications