name: Release

on:
  workflow_dispatch

jobs:
  BumpVersion:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    env:
      CI: true
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Check if branch is master
        run: |
          if [[ "${GITHUB_REF##*/}" != "master" ]]; then
            echo "This workflow can only be triggered for the master branch."
            exit 1
          fi
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  Release:
    needs: BumpVersion
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew clean build
    
      - name: Execute Gradle publish
        run: ./gradlew publish

      - name: Execute Gradle release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: ./gradlew jreleaserFullRelease

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            build/libs
            build/publications